function ReplaceNumberWithCommas(yourNumber){var components=yourNumber.toString().split(".");components[0]=components[0].replace(/\B(?=(\d{3})+(?!\d))/g,",");return components.join(".");}
function facebookShares($URL){$.getJSON('https://graph.facebook.com/?id='+$URL,function(fbdata){if(fbdata.shares==undefined){fbdata.shares=0;}
$('#totalsharing').attr('data-facebookShares',fbdata.shares);});}
function twitterShares($URL){$('#totalsharing').attr('data-twitterShares',0);}
function linkdInShares($URL){$.getJSON('https://www.linkedin.com/countserv/count/share?url='+$URL+'&callback=?',function(linkdindata){$('#totalsharing').attr('data-linkdInShares',linkdindata.count);});}
function checkJSON_getSum(){if($('#totalsharing').attr('data-facebookShares')!=undefined&&$('#totalsharing').attr('data-twitterShares')!=undefined&&$('#totalsharing').attr('data-linkdinshares')!=undefined){var fbShares=parseInt($('#totalsharing').attr('data-facebookShares'));var twitShares=parseInt($('#totalsharing').attr('data-twitterShares'));var linkdInShares=parseInt($('#totalsharing').attr('data-linkdinshares'));var totalShares=fbShares+twitShares+linkdInShares;$('#totalsharing').text(ReplaceNumberWithCommas(totalShares)+' shares');}
else{setTimeout(function(){checkJSON_getSum();},200);}}
function totalShares($URL){linkdInShares($URL);twitterShares($URL);facebookShares($URL);checkJSON_getSum();}
$(document).on('click','.yamm .dropdown-menu',function(e){e.stopPropagation()});$(function(){$("#dayplanner").sortable();$("#dayplanner").disableSelection();});$(document).ready(function(){$(document).delegate('*[data-toggle="lightbox"]','click',function(event){event.preventDefault();$(this).ekkoLightbox({left_arrow_class:'.fa .fa-chevron-left',right_arrow_class:'.fa .fa-chevron-right',gallery_parent_selector:'.story-detail'});});$(".faq h4").click(function(){$(this).next('.answer').stop().slideToggle("fast",function(){});});$(".add_to_itinerary").each(function(){var btn=$(this);var item_url=btn.attr("data-url");var item_name=btn.attr("data-name");if(item_url!==undefined&&item_name!==undefined){btn.click(function(e){e.preventDefault();btn.html('<i class="fa fa-cog fa-spin"></i>');$.post('/itinerary/add',{url:item_url,name:item_name},function(response){if(response=='SUCCESS'){btn.text('Added');btn.unbind('click');btn.attr("href","/itinerary");btn.siblings('.circle-div').css("transition","all 0.5s").css("opacity",0).css("transform","scale(2)");$(".itinerary-count").each(function(){$(this).text(parseInt($(this).text())+1);});}else{console.log(response);btn.text('Sorry, something went wrong');}});});}});$('.toggle-menu').jPushMenu({closeOnClickLink:false,closeOnClickInside:false,closeOnClickOutside:false});$('.dropdown-toggle').dropdown();$('.navbar-default .navbar-nav > li > a').on("click",function(){var navWidth=$(this).outerWidth()
var menuPosition=$(this).offset();var xPos=menuPosition.left;var menuWidth=$(this).next().outerWidth()-navWidth;if(xPos>=700){$(this).next().css('left',-menuWidth);}});wow=new WOW({boxClass:'wow',animateClass:'animated',offset:0,mobile:false,live:true})
wow.init();var mobMenu=false;$(".toggle-menu").on("click",function(){if(mobMenu==false){$(".cbp-spmenu").prependTo(".mob-menu");mobMenu=true;$('body').addClass('menu-open');}else{$(".cbp-spmenu").prependTo(".desktop-menu");mobMenu=false;$('body').removeClass('menu-open');}});$(document).on('click',function(e){$(".cbp-spmenu").prependTo(".desktop-menu");$('.jPushMenuBtn,body,.cbp-spmenu').removeClass('disabled active cbp-spmenu-open cbp-spmenu-push-toleft cbp-spmenu-push-toright menu-open');mobMenu=false;});$(".back").on("click",function(e){e.preventDefault();$('.jPushMenuBtn,body,.cbp-spmenu').removeClass('disabled active cbp-spmenu-open cbp-spmenu-push-toleft cbp-spmenu-push-toright menu-open');$(".cbp-spmenu").prependTo(".desktop-menu");mobMenu=false;});panelheight();function panelheight(){setTimeout(function(){if($(window).width()>=992){var newsBottom=$('.news-cols').offset().top+$('.news-cols').outerHeight(true);var eventsBottom=$('.event-cols').offset().top+$('.event-cols').outerHeight(true);var difference=newsBottom-eventsBottom;var newHeight=difference+$('.event-cols').outerHeight(true);$('.event-cols .panel-body').css('height',newHeight-15);}else{$('.event-cols .panel-body').css('height','auto');}},1000);}
window.addEventListener("resize",function(){$('.jPushMenuBtn,body,.cbp-spmenu').removeClass('disabled active cbp-spmenu-open cbp-spmenu-push-toleft cbp-spmenu-push-toright menu-open');$(".cbp-spmenu").prependTo(".desktop-menu");mobMenu=false;smallRes();panelheight();setTimeout(bannerTxt,500);},false);setTimeout(bannerTxt,500);function bannerTxt(){if($(window).width()<767){$('.banner-title-top').css("bottom","0px");}else if(($(window).width()>=992)&&($(window).width()<=1380)){$('.banner-title-top').css("bottom",-110+"px");}else{var sliderHeight=$(".vision-slider .item img").height()-($('.banner-title-top').height()+15);$('.banner-title-top').css("bottom",sliderHeight+"px");}}
smallRes();function smallRes(){if($(window).width()>767&&$(window).width()<992){$(".move-small").appendTo(".news-cols");}else{$(".move-small").prependTo(".move-small-back");}}
var bannerSlider=$('.vision-slider');bannerSlider.owlCarousel({items:1,lazyLoad:false,loop:true,autoplay:true,autoplayTimeout:6000,dots:true,callbacks:true,responsiveClass:true,margin:0,responsive:{0:{items:1,nav:true}}});var bannerSlider2=$('.vision-slider2');bannerSlider2.owlCarousel({items:1,lazyLoad:false,loop:true,autoplay:true,autoplayTimeout:6000,dots:false,callbacks:true,responsiveClass:true,margin:0,responsive:{0:{items:1,nav:true}}});$(".vision-slider-arrows .next").click(function(){bannerSlider2.trigger('next.owl.carousel');});$(".vision-slider-arrows .prev").click(function(){bannerSlider2.trigger('prev.owl.carousel');});var stickyNavTop=$('.fixednavbar').offset().top;var stickyNav=function(){var scrollTop=$(window).scrollTop();if(scrollTop>stickyNavTop&&window.innerWidth>=992){$('.fixednavbar').addClass('sticky');var height=$('.fixednavbar').height();$('#header').css('padding-bottom',height+'px');}else{$('.fixednavbar').removeClass('sticky');$('#header').css('padding-bottom','');}};stickyNav();$(window).scroll(function(){stickyNav();});$(".list-group-item.dropdown > a").click(function(e){e.preventDefault();$(this).siblings(".list-group-children").stop().slideToggle(300);});$(".panel-submenu .open-children").parent().show().parent().show();$("form.ajax_submit").each(function(){var $this=$(this);$this.submit(function(e){e.preventDefault();var $data=$this.serialize();$data+="&ajax=1";console.log($this.attr("action"));$.ajax({url:$this.attr("action"),type:'post',data:$data,success:function(response){console.log(response);response=JSON.parse(response);alert(response.message);if(response.success==true){$this.html(response.message);}
console.log(response);}});});});$('#submitcomp').click(function(){$('#submitcomp').html('<i class="fa fa-spin fa-spinner" style="font-size: 50px;"></i>');if($("#competition_option_id").length==0){var competition_option_id=null;}else{var competition_option_id=$('#competition_option_id').val();}
if($("#imagename").length==0){var imagename=null;}else{var imagename=$('#imagename').val();}
if($("#textanswer").length==0){var textanswer=null;}else{var textanswer=$('#textanswer').val();}
var parent=0;if($('#compparent:checked').length>0){parent=1;}
var optIn=0;if($('#compoptin:checked').length>0){optIn=1;}
if($("#compterms:checked").length<1){swal("Oh no!","Please make sure you have read and accept the terms and conditions","error");$('#submitcomp').html('Submit my entry!');}else{var data={'name':$('#compname').val(),'email':$('#compemail').val(),'postcode':$('#comppostcode').val(),'date_of_birth':$('#compdob').val(),'parent':parent,'opt_in':optIn,'competition_option_id':competition_option_id,'competition_id':$('#competition_id').val(),'imagename':imagename,'text_answer':textanswer};$.ajax({type:"POST",data:data,url:'/explore/competitions/process_entry',success:function(data){var obj=JSON.parse(data);console.log(obj);if(obj.result==true){$('#enterform').slideUp(500);swal("Good job!",obj.message,"success");$('#entermessage').slideUp(500);$('#successend').slideDown(500);}else{$('#submitcomp').html('Submit my entry!');$('#enterform').slideDown(500);swal("Oh no!",obj.message,"error");$('#entermessage').addClass('errormessage').html(obj.message);}}});}});});$(function(){if($(window).width()<992){$(".dropdown-menu li.trigger > a").on("click",function(e){e.preventDefault();e.stopPropagation();$(this).closest('.dropdown').toggleClass('open');});$('.dropdown .trigger a').on("click",function(){if($(this).parent().hasClass('open')){}
else{$('.trigger').removeClass('open');}});}});